# NOTE:THIS DID NOT WORK WITH MAKING A FIRST ALEMBIC VERSION
services:
  postgres:
    image: postgres:16
    container_name: gdb-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: gdb
      POSTGRES_PASSWORD: gdbpass
      POSTGRES_DB: gdb
    ports:
      - "5432:5432"
    volumes:
      - gdb_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "gdb"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  gdb_pgdata:
    name: gdb_pgdata