"""initial setup

Revision ID: 581ff4572869
Revises: 
Create Date: 2026-02-15 11:29:08.879802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '581ff4572869'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('primary_contact', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('secondary_contact', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_channels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('about_node_name', sa.String(), nullable=False),
    sa.Column('captured_by_node_name', sa.String(), nullable=False),
    sa.Column('telemetry_name', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('in_power_metering', sa.Boolean(), nullable=True),
    sa.Column('terminal_asset_alias', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('terminal_asset_alias', 'about_node_name', 'captured_by_node_name', 'telemetry_name', name='unique_triple_per_ta'),
    sa.UniqueConstraint('terminal_asset_alias', 'name', name='unique_name_terminal_asset')
    )
    op.create_table('installers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('from_alias', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('persisted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message_type_name', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', 'timestamp'),
    timescaledb_hypertable={'time_column_name': 'timestamp'}
    )
    op.create_index('ix_from_type_message', 'messages', ['from_alias', 'message_type_name', 'persisted_at'], unique=False)
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    op.create_index('messages_timestamp_idx', 'messages', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_table('position_points',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('latitude_micro_deg', sa.Integer(), nullable=False),
    sa.Column('longitude_micro_deg', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('g_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('prev_alias', sa.String(), nullable=True),
    sa.Column('base_class', sa.Enum('TerminalAsset', 'LeafTransactiveNode', 'ConnectivityNode', 'MarketMaker', 'Logical', name='base_g_node_class'), nullable=True),
    sa.Column('g_node_class', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Active', 'PermanentlyDeactivated', 'Suspended', name='g_node_status'), nullable=False),
    sa.Column('position_point_id', sa.Uuid(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['position_point_id'], ['position_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_g_nodes_alias'), 'g_nodes', ['alias'], unique=True)
    op.create_table('readings',
    sa.Column('data_channel_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['data_channel_id'], ['data_channels.id'], )
    )
    op.create_index(op.f('ix_readings_message_id'), 'readings', ['message_id'], unique=False)
    op.create_index(op.f('ix_readings_timestamp'), 'readings', ['timestamp'], unique=False)
    op.create_index('readings_timestamp_idx', 'readings', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_table('connectivity_edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_g_node_id', sa.Uuid(), nullable=False),
    sa.Column('to_g_node_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Active', 'PermanentlyDeactivated', 'Suspended', name='connectivity_edge_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_g_node_id'], ['g_nodes.id'], ),
    sa.ForeignKeyConstraint(['to_g_node_id'], ['g_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_g_node_id', 'to_g_node_id', name='uq_connectivity_edges_from_to')
    )
    op.create_index(op.f('ix_connectivity_edges_from_g_node_id'), 'connectivity_edges', ['from_g_node_id'], unique=False)
    op.create_index(op.f('ix_connectivity_edges_to_g_node_id'), 'connectivity_edges', ['to_g_node_id'], unique=False)
    op.create_table('spaceheat_installations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('g_node_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('installer_id', sa.Uuid(), nullable=False),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('alert_status', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hardware_layout', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('representation_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('house_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scada_ip_address', sa.String(), nullable=True),
    sa.Column('scada_git_commit', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['g_node_id'], ['g_nodes.id'], ),
    sa.ForeignKeyConstraint(['installer_id'], ['installers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.execute("SELECT create_hypertable('messages', by_range('timestamp'))")
    op.execute("SELECT create_hypertable('readings', by_range('timestamp'))")
    op.execute("""
        ALTER TABLE readings SET(
            timescaledb.enable_columnstore, 
            timescaledb.orderby = 'timestamp DESC', 
            timescaledb.segmentby = 'data_channel_id')
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spaceheat_installations')
    op.drop_index(op.f('ix_connectivity_edges_to_g_node_id'), table_name='connectivity_edges')
    op.drop_index(op.f('ix_connectivity_edges_from_g_node_id'), table_name='connectivity_edges')
    op.drop_table('connectivity_edges')
    op.drop_index('readings_timestamp_idx', table_name='readings')
    op.drop_index(op.f('ix_readings_timestamp'), table_name='readings')
    op.drop_index(op.f('ix_readings_message_id'), table_name='readings')
    op.drop_table('readings')
    op.drop_index(op.f('ix_g_nodes_alias'), table_name='g_nodes')
    op.drop_table('g_nodes')
    op.drop_table('users')
    op.drop_table('position_points')
    op.drop_index('messages_timestamp_idx', table_name='messages')
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_index('ix_from_type_message', table_name='messages')
    op.drop_table('messages')
    op.drop_table('installers')
    op.drop_table('data_channels')
    op.drop_table('customers')
    # ### end Alembic commands ###

    op.execute('DROP TYPE base_g_node_class')
    op.execute('DROP TYPE g_node_status')
    op.execute('DROP TYPE connectivity_edge_status')
