"""visualizer functions and views

Revision ID: a7f151e8163f
Revises: 1220f2f941dd
Create Date: 2026-06-18 10:34:33.737411

"""
import os
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f151e8163f'
down_revision: Union[str, Sequence[str], None] = '1220f2f941dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###

    op.execute("GRANT UPDATE (last_login, updated_at) ON gridworks.users TO gw_visualizer;")

    op.execute("CREATE FUNCTION gridworks.c2f(temp_c FLOAT) RETURNS FLOAT IMMUTABLE LANGUAGE 'sql' RETURN temp_c * 9.0 / 5.0 + 32;")
    op.execute("CREATE FUNCTION gridworks.f2c(temp_f FLOAT) RETURNS FLOAT IMMUTABLE LANGUAGE 'sql' RETURN (temp_f - 32) * 5.0 / 9.0;")

    misc_scripts_folder = os.path.join(
        os.path.dirname(__file__), 
        '../../src/gw_data/db/scripts/misc/',
    )

    for script in [
        'create_view_readings_1hr.sql',
        'create_policy_view_readings_1hr.sql',
        'create_udf_retrieve_readings_1s.sql',
        'create_udf_calc_energy_1hr.sql',
        'create_udf_calc_hourly_data.sql',
        'create_table_cached_hourly_data.sql',
        'create_proc_refresh_cached_hourly_data.sql'
    ]:
        with open(os.path.join(misc_scripts_folder, script), 'r') as f:
            sql = f.read().strip()
            op.execute(sql)
        

    op.execute("SELECT add_job('gridworks.refresh_cached_hourly_data', INTERVAL '30 minutes');")

    print("""
          IMPORTANT: to populate existing data into the `gridworks.readings_1hr` continuous aggregate, you must manually run `refresh_continuous_aggregate`.
          IMPORTANT: to populate existing data into the `gridworks.cached_hourly_data` table, you will need to run `refresh_all_cached_hourly_data.py`.
          """)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###

    op.execute("SELECT delete_job((SELECT job_id FROM timescaledb_information.jobs WHERE proc_schema = 'gridworks' AND proc_name = 'refresh_cached_hourly_data'));")
    op.execute('DROP PROCEDURE gridworks.refresh_cached_hourly_data;')
    op.execute('DROP TABLE gridworks.cached_hourly_data;')
    op.execute('DROP FUNCTION gridworks.calc_hourly_data;')
    op.execute('DROP MATERIALIZED VIEW gridworks.readings_1hr;')
    op.execute('DROP FUNCTION gridworks.retrieve_readings_1s(timestamp with time zone, timestamp with time zone, text[]);')
    op.execute('DROP FUNCTION gridworks.calc_energy_1hr(timestamp with time zone, timestamp with time zone);')
    op.execute('DROP FUNCTION gridworks.c2f(float)')
    op.execute('DROP FUNCTION gridworks.f2c(float)')
